sources:
  - name: my_snowflake
    database: EDW_DEV
    schema: RAW
    tables: 
      - name: nse_stock
        identifier: nse_stock_daily_data
      - name: emp_json
      - name: CLONE_ORDERS
  - name: orders
    database: EDW_DEV
    schema: RAW
    tables:
      - name: sample_flatten_orders